### ISSUE TITLE
Can support mult-language?

### ISSUE THREAD

**Issue by JIJL** [joeferner/redis-commander#299] opened 2018-10-20 02:35 UTC
when i search for key，I got the garbled value，like this 
`��srjava.util.ArrayListx����a�Isizexpwsrjava.util.HashMap���`�F`

**Comment by sseide** [comment] 2019-02-08 16:22
Seems to be binary data stored inside redis. There is no special handling right now for binary data, therefor no workaround available.

duplicate of #140

If its no binary data (check with redis-cli or similiar) please reopen issue with some more informations about the data stored inside redis.

**Closed by sseide** 2019-02-08 16:22 UTC
Labels: duplicate
