### ISSUE TITLE
Unable to connect Remote Redis

### ISSUE THREAD

**Issue by cah-manish-kumar05** [joeferner/redis-commander#402] opened 2020-04-13 14:21 UTC
While Trying to connect Remote Redis instance hosted on PCF Shared VM, its failing with time out error as below -
`Redis error Error: connect ETIMEDOUT`

**Comment by sseide** [comment] 2020-04-16 08:44
as message states the redis commander container cannot talk to your redis server. Without further infos we cannot really help.

Therefore please check:
* port configured is the port the redis server listens to
* dns-name or ip given to redis commander as redis server is correct
* dns-name can be resolved from inside the container
* final ip address the server name resolves to can be reached from inside the container (ip route exists and no firewall is blocking communications)

**Comment by sseide** [comment] 2020-06-02 11:52
Issue closed by now?

**Comment by sseide** [comment] 2020-06-15 16:48
close (no feedback and unable to reproduce)

**Closed by sseide** 2020-06-15 16:48 UTC
