### ISSUE TITLE
100% CPU hang on initial render on Windows 7

### ISSUE THREAD

**Issue by sming** [joeferner/redis-commander#154] opened 2015-05-05 14:24 UTC
Hi,

I can successfully query our redis server via redis-cli but not through redis-commander.  

Upon requesting 127.0.0.1:8082 (where redis-commander is listening), node.exe jumps to 100% CPU and the page hangs.  When I kill node.exe, a partial response is received by the browser (s/s attached).

Any ideas?
Thanks, Pete
![redos](https://cloud.githubusercontent.com/assets/1403866/7474661/cd183780-f310-11e4-9efa-04a686f2083e.PNG)

**Comment by okcompute** [comment] 2015-05-05 15:52
I got the same issue with the latest version (0.3.0) on Win7 64 bits. I also got this weird message now:

   > redis-commander
    No Save: false
    listening on  0.0.0.0 : 8081

Port 0.0.0.0! Strange! Any ideas?

**Comment by azzlack** [comment] 2015-05-18 11:27
Same here. Uses a lot of cpu, and just hangs

**Comment by sseide** [comment] 2019-02-08 16:00
This problem should be fixed in current version. 
If you think its not feel free to reopen issue with updated informations based on latest version.

Problem may be caused by large redis database too. Try using `--use-scan` cli param or config value
to minimize initial load time on connect.

**Closed by sseide** 2019-02-08 16:00 UTC
