### ISSUE TITLE
Bad JS load path when URL missing trailing slash

### ISSUE THREAD

**Issue by mcandre** [joeferner/redis-commander#419] opened 2020-10-22 14:59 UTC
Remember to prefix assets with a forward slash so that they're not relative. Blank white screen.

**Comment by sseide** [comment] 2020-10-27 10:21
some more information please? Where exactly do you spotted this problem?

**Comment by sseide** [comment] 2020-12-19 19:07
As this report was not really descriptive and I could not reproduce it, i'm not sure if your problem may be fixed with latest version. Added validation to urlPrefix there...

**Comment by sseide** [comment] 2021-03-10 22:50
closed as there is no feedback and i believe its fixed with later releases. Please reopen with more details if not fixed

**Closed by sseide** 2021-03-10 22:50 UTC
