### ISSUE TITLE
charcter problems in key value window

### ISSUE THREAD

**Issue by gitdexby** [joeferner/redis-commander#193] opened 2017-03-31 18:24 UTC
For some reason, I'm getting these strange chars in the value window. I'm not sure where to go with this. I checked the config options for running the server as it relates to content-type (wild guess). But not seeing anything that might help here.

Also did some searching through the 'Issues' and didn't find any leads here either.

![screenshot_2017-03-31_13-15-17](https://cloud.githubusercontent.com/assets/1420209/24563503/22755bae-1614-11e7-9e24-9cb567512cc5.png)

Suggestions?

Specs:
---------
- Linux dave-macbook-linux 4.8.0-36-generic #36~16.04.1-Ubuntu SMP Sun Feb 5 09:39:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Firefox 52.0.2 (64-bit)
- Chrome Version 57.0.2987.110 (64-bit)
- Just did an npm install again to re-verify (do I need to first remove a previous version? npm newbie)

**Comment by sseide** [comment] 2019-02-08 16:21
Seems to be binary data stored inside redis. There is no special handling rigght now for binary data, therefor no workaround available.

duplicate of #140 

If its no binary data (check with redis-cli or similiar) please reopen issue with some more informations about the data stored inside redis.

**Closed by sseide** 2019-02-08 16:21 UTC
Labels: duplicate
