### ISSUE TITLE
right pane is stuck in loading

### ISSUE THREAD

**Issue by edib** [joeferner/redis-commander#459] opened 2021-11-15 06:20 UTC
I have installed redis-commander a kubernetes deployment. I have supplied redis info at startup. 
the terminal in the ui is working well, server info on the right pane is valid but left panel tree is not working, stuck in loading. 
JS console in browser produces following error. 

Uncaught DOMException: Element.querySelector: '#R\:10\.0\.0\.21\:6379\:0\:����t�
SID_ST_MAP' is not a valid selector

**Comment by sseide** [comment] 2021-11-15 08:40
duplicate of #425 and also related to #454 (same base problem)

**Closed by sseide** 2021-11-15 08:40 UTC
Labels: duplicate
