### ISSUE TITLE
Refreshing page requires re-login. Trying to add server returns "Unauthorized - Missing Token"

### ISSUE THREAD

**Issue by lsattem** [joeferner/redis-commander#292] opened 2018-10-12 10:48 UTC
Errors in title. 
When I try to add a server via the interface a new page is opened that simply says "Unauthorized - Missing Token". And if i try to refresh the page it asks me to log in again.

Compose file:

```
version: '3'
services:
    redis:
        container_name: redis
        hostname: redis
        image: redis

  redis-commander:
      container_name: redis-commander
      hostname: redis-commander
      image: rediscommander/redis-commander:latest
      restart: always
      environment:
          - REDIS_HOST=local:redis:6379
          - HTTP_USER=test
          - HTTP_PASSWORD=test
      ports:
          - "8081:8081"
```

**Comment by sseide** [comment] 2018-10-12 15:55
created pull request to fix this...

**Comment by sseide** [comment] 2018-10-16 12:30
Please retest with latest version from github or docker image. Does it work now?

**Comment by sseide** [comment] 2018-10-17 09:00
Got this behaviour with relogin after the first PR #293 too. But should not be necessary anymore with update from yesterday. At least i could not reproduce it anymore.

If you must relogin with latest version please provide some more informations about your environment (browser/os etc. too) so i may fix it finally...

Thanks

**Comment by lsattem** [comment] 2018-10-17 09:51
Not sure exactly what to provide, but:

Using Chrome 67.0.3396.87 on Windows 7. Running redis-commander in Ubuntu 16.04 via Docker as described in the compose file in the original post.

**Comment by sseide** [comment] 2018-10-18 13:28
not really shure if i could reproduce (client was win7 with chrome 69&70 as well as Firefox). But found some small things regarding addServer and login functionality. 

Can you please retry with latest docker image?

**Comment by lsattem** [comment] 2018-10-19 07:15
Still the same. Refreshing requires re-login. I get the same in Firefox Nightly.

**Comment by sseide** [comment] 2018-10-19 09:07
Just to be shure i understand correctly what you mean with refreshing...

There was a timing problem at some browsers:
-> Open "Add server"
-> enter new server data
-> hit connect
-> now server is added and page automatically refreshed/reloaded to redisplay the tree list with all servers. But you must relogin now. This should be fixed (at least could not reproduce after last changes).

What do you mean with "refreshing"? Hitting F5 in browser or pressing the browsers reload button (not the green refresh button from redis commander). This does indeed trigger a relogin. But that is intended behaviour for security reason...

**Comment by lsattem** [comment] 2018-10-19 09:10
Ah. That is what i was referring to. So if that was intended behaviour then I'm sorry, and this can be closed :)

**Comment by sseide** [comment] 2018-10-19 09:17
Ok :-) But due to it i found this timing issue. 

The access token get automatically deleted from localStorage when you leave the page (mainly for closing browser etc) To not allow others to just access your browser when you are not watching and reusing your old login...

There should be no reason to hit F5 within the app, or? 
Than it can be closed i believe...

**Comment by sseide** [comment] 2019-02-08 16:03
This problem should be fixed in current version. 
If you think its not feel free to reopen issue with updated informations based on latest version.

**Closed by sseide** 2019-02-08 16:03 UTC
